FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest pytest-asyncio

COPY app ./app
COPY tests ./tests
COPY pytest.ini .

CMD ["pytest", "tests/", "-v"]
